# -*- coding: utf-8 -*-
"""600747_ลัญจกร_Hack3_Ver2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15pDEHvghIDHXJ_6b1UMh-4tmdxGykxCK
"""

!pip install -q sentence-transformers pythainlp rank-bm25 requests python-dotenv pandas tqdm torch transformers accelerate bitsandbytes langchain langchain-text-splitters faiss-cpu openpyxl pacmap datasets langchain-community ragatouille

import os
from google.colab import userdata

# 1. ดึง Username และ Key จาก Secrets มาตั้งเป็น Environment Variables
os.environ['KAGGLE_USERNAME'] = userdata.get('KAGGLE_USER')
os.environ['KAGGLE_KEY'] = userdata.get('KAGGLE_KEY')

# 2. ดาวน์โหลดและแตกไฟล์ข้อมูลการแข่งขัน
!kaggle competitions download -c super-ai-engineer-s-6-fah-mai-rag-challenge-level-1
!unzip -q -o super-ai-engineer-s-6-fah-mai-rag-challenge-level-1.zip -d fahmai_data

# 3. เช็คว่าไฟล์เข้ามาครบไหม
!ls fahmai_data

import torch
# 4. เช็ค GPU
if torch.cuda.is_available():
    print(f"✅ เปิดใช้งาน GPU สำเร็จ! รุ่นที่ได้คือ: {torch.cuda.get_device_name(0)}")
else:
    print("❌ ยังไม่ได้เปิด GPU หรือระบบยังเชื่อมต่อไม่เสร็จ กรุณาเช็คเมนู Runtime อีกครั้งครับ")

import os
import glob
import re
import time
import requests
import json
import numpy as np
import pandas as pd
import torch
from tqdm.auto import tqdm
from google.colab import drive
from langchain_text_splitters import MarkdownHeaderTextSplitter, RecursiveCharacterTextSplitter
from pythainlp.tokenize import word_tokenize
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer, CrossEncoder
from collections import deque

# ==========================================
# 0. CONFIGURATION & TUNING
# ==========================================
THAILLM_API_KEY = userdata.get('ThaiLLM') # ⚠️ ใส่ API Key ของคุณ

DATA_DIR = "fahmai_data"
CHUNK_SIZE = 1024
CHUNK_OVERLAP = 128
FETCH_K = 20 # จำนวนดึงข้อมูลรอบแรก (ต่อ 1 คำค้นหา)

MODELS_TO_TEST = [
    "openthaigpt",
    "pathumma",
    "typhoon",
    "kbtg"
]

# ==========================================
# 1. ADVANCED DATA PIPELINE (Table Unrolling & Metadata)
# ==========================================
print("📦 [Step 1] Loading and performing Advanced Data Ingestion...")

def unroll_markdown_table(text):
    lines = text.split('\n')
    unrolled, in_table, headers = [], False, []

    for line in lines:
        if line.strip().startswith('|') and line.strip().endswith('|'):
            cells = [c.strip() for c in line.split('|')[1:-1]]
            if not in_table:
                headers = cells
                in_table = True
            elif set(list(line.strip())) <= set(['|', '-', ' ', ':']):
                continue
            else:
                row_data = [f"{headers[i]}: {cell}" for i, cell in enumerate(cells) if i < len(headers) and cell and cell != "-"]
                unrolled.append("📌 ข้อมูลสเปค -> " + " | ".join(row_data))
        else:
            in_table = False
            unrolled.append(line)
    return '\n'.join(unrolled)

def clean_text_normalization(text):
    text = re.sub(r'\[([^\]]+)\]\([^\)]+\)', r'\1', text)
    return unroll_markdown_table(text)

md_files = glob.glob(f"{DATA_DIR}/**/*.md", recursive=True)

headers_to_split_on = [("#", "หมวดหมู่หลัก"), ("##", "หัวข้อย่อย 1"), ("###", "หัวข้อย่อย 2")]
markdown_splitter = MarkdownHeaderTextSplitter(headers_to_split_on=headers_to_split_on)
text_splitter = RecursiveCharacterTextSplitter(chunk_size=CHUNK_SIZE, chunk_overlap=CHUNK_OVERLAP, separators=["\n\n", "\n", " ", ""])

chunk_texts = []
for file_path in tqdm(md_files, desc="Processing Markdown Files"):
    filename = os.path.basename(file_path)
    with open(file_path, 'r', encoding='utf-8') as f:
        raw_text = clean_text_normalization(f.read())
        md_header_splits = markdown_splitter.split_text(raw_text)
        final_splits = text_splitter.split_documents(md_header_splits)

        for split in final_splits:
            metadata_str = f"[อ้างอิงเอกสาร: {filename}]"
            if "หมวดหมู่หลัก" in split.metadata: metadata_str += f" > {split.metadata['หมวดหมู่หลัก']}"
            if "หัวข้อย่อย 1" in split.metadata: metadata_str += f" > {split.metadata['หัวข้อย่อย 1']}"
            chunk_texts.append(f"{metadata_str}\n{split.page_content}")

print(f"✅ Created {len(chunk_texts)} highly contextualized chunks.")

print("🧠 [Step 2] Initializing Hybrid Retrievers & Reranker...")

print("  ⏳ Building BM25 Index...")
tokenized_chunks = [word_tokenize(text, engine="newmm") for text in tqdm(chunk_texts, desc="Tokenizing for BM25")]
bm25 = BM25Okapi(tokenized_chunks)

print("  ⏳ Loading Dense Model (mE5-large)...")
embed_model = SentenceTransformer('intfloat/multilingual-e5-large')
chunk_embeddings = embed_model.encode([f"passage: {t}" for t in chunk_texts],show_progress_bar=True, normalize_embeddings=True)

print("  ⏳ Loading Reranker (BGE-M3)...")
reranker = CrossEncoder('BAAI/bge-reranker-v2-m3')
print("  ✅ All Retrieval components are fully loaded.")

def hybrid_retrieve(original_query, expanded_queries=[], fetch_k=FETCH_K):
    all_queries = [original_query] + expanded_queries
    bm25_idx = set()
    dense_idx = set()

    global chunk_embeddings
    if not torch.is_tensor(chunk_embeddings):
        chunk_embeddings = torch.tensor(chunk_embeddings)

    for q in all_queries:
        # Sparse (BM25)
        tokens = word_tokenize(q, engine="newmm")
        bm25_idx.update(np.argsort(bm25.get_scores(tokens))[::-1][:fetch_k])

        # Dense (mE5)
        q_emb = embed_model.encode(f"query: {q}", normalize_embeddings=True, convert_to_tensor=True).to(chunk_embeddings.device)
        chunk_embeddings = chunk_embeddings.to(q_emb.device)
        dense_scores = torch.matmul(q_emb, chunk_embeddings.T).squeeze(0)
        dense_idx.update(torch.topk(dense_scores, k=fetch_k).indices.cpu().numpy())

    candidate_indices = list(bm25_idx.union(dense_idx))
    candidate_texts = [chunk_texts[i] for i in candidate_indices]

    # Rerank ด้วยคำถามต้นฉบับเท่านั้น
    cross_inp = [[original_query, text] for text in candidate_texts]
    rerank_scores = reranker.predict(cross_inp)
    sorted_idx = np.argsort(rerank_scores)[::-1]

    # --- 🌟 Dynamic TOP_K (เลือกเฉพาะข้อมูลที่มีคะแนนเกาะกลุ่มกับที่ 1) ---
    best_score = rerank_scores[sorted_idx[0]]
    best_texts = []

    for idx in sorted_idx[:5]: # ดึงมาสูงสุดไม่เกิน 5 ก้อน
        # หากคะแนนห่างจากที่ 1 ไม่เกิน 2.5 logit ถือว่าเป็นข้อมูลที่เกี่ยวข้อง
        if rerank_scores[idx] >= best_score - 2.5:
            best_texts.append(candidate_texts[idx])

    return "\n\n---\n\n".join(best_texts)

print("⚙️ [Step 3] Setting up API, HyDE & CoT Parser...")

request_timestamps = deque()

def wait_for_rate_limit():
    global request_timestamps
    now = time.time()
    while request_timestamps and now - request_timestamps[0] >= 60: request_timestamps.popleft()
    if len(request_timestamps) >= 200:
        sleep_time = 60 - (now - request_timestamps[0])
        if sleep_time > 0: time.sleep(sleep_time)
        now = time.time()
    if request_timestamps and now - request_timestamps[-1] < 0.2:
        sleep_time = 0.2 - (now - request_timestamps[-1])
        if sleep_time > 0: time.sleep(sleep_time)
        now = time.time()
    request_timestamps.append(now)

def ask_llm(messages, model, max_tokens=2024, max_retries=5):

    url = f"http://thaillm.or.th/api/{model}/v1/chat/completions"
    headers = {"Content-Type": "application/json", "apikey": THAILLM_API_KEY}
    payload = {"model": "/model", "messages": messages, "max_tokens": max_tokens, "temperature": 0.0}

    for attempt in range(max_retries):
        try:
            resp = requests.post(url, headers=headers, json=payload, timeout=120)

            # Rate limit — wait and retry
            if resp.status_code == 429:
                wait = min(2 ** attempt, 30)
                print(f"  Rate limited, waiting {wait}s...")
                time.sleep(wait)
                continue

            resp.raise_for_status()
            return resp.json()["choices"][0]["message"]["content"].strip()

        except requests.exceptions.RequestException as e:
            wait = 2 ** attempt
            print(f"  Error: {e}, retrying in {wait}s...")
            time.sleep(wait)

    return None

def generate_expanded_queries(query):
    sys_prompt = "คุณคือ AI ผู้ช่วยค้นหาข้อมูล หน้าที่ของคุณคือสร้าง 'คำค้นหา (Search Keyword)' เพิ่มเติม 2 ประโยคจากคำถามที่ให้มา เพื่อนำไปใช้ค้นหาสเปคสินค้าใน Database ตอบกลับแค่คำค้นหา 2 ประโยคคั่นด้วยเครื่องหมายจุลภาค (,) ห้ามมีคำอธิบายใดๆ"
    messages = [{"role": "system", "content": sys_prompt}, {"role": "user", "content": query}]
    ans = ask_llm(messages, model="typhoon", max_tokens=100, max_retries=3) # ใช้ typhoon เป็นตัวสร้าง Query
    if ans: return [q.strip() for q in ans.split(",") if q.strip()]
    return []

def parse_cot_answer(text):
    if text is None: return 9, False
    clean_text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()
    match = re.search(r'Answer:\s*([1-9]|10)', clean_text, re.IGNORECASE)
    if match: return int(match.group(1)), True
    numbers = re.findall(r'\b(?:10|[1-9])\b', clean_text)
    if numbers: return int(numbers[-1]), True
    return 9, False

print("✅ API, HyDE, and CoT Parser initialized.")

print("🚀 [Step 4] Starting Ultimate Inference Pipeline...")

# --- 1. MOUNT GOOGLE DRIVE ---
drive.mount('/content/drive')
DRIVE_SAVE_DIR = '/content/drive/MyDrive/FahMai_RAG_Results'
os.makedirs(DRIVE_SAVE_DIR, exist_ok=True)
CHECKPOINT_PATH = os.path.join(DRIVE_SAVE_DIR, 'rag_checkpoint.json')

# --- 2. LOAD QUESTIONS ---
found_csvs = glob.glob("**/questions.csv", recursive=True)
if not found_csvs: raise FileNotFoundError("⚠️ Error: ไม่พบไฟล์ questions.csv")
df_questions = pd.read_csv(found_csvs[0])

# --- 🌟 อัปเกรด System Prompt (Few-Shot + Chain of Thought) ---
sys_prompt = """คุณคือผู้เชี่ยวชาญระดับสูงของร้านอุปกรณ์อิเล็กทรอนิกส์ "ฟ้าใหม่" (FahMai)
จงวิเคราะห์ [Context] เพื่อตอบ [Question] โดยเลือกจาก [Choices] 1-10

กฎเหล็ก:
- หากคำถามเป็นเรื่องทั่วไปที่ไม่เกี่ยวกับร้านฟ้าใหม่เลย ให้ตอบ 10
- หากข้อมูลใน [Context] ไม่มีคำตอบที่ชัดเจน หรือมีข้อมูลไม่ครบถ้วนพอที่จะฟันธง ให้ตอบ 9
- หากพบข้อมูลตรงกัน ให้เลือกตัวเลข 1-8 ที่ถูกต้องที่สุด

ตัวอย่างการคิด:
[Question]: แอร์บุ๊ก 14 มีกี่สี?
[Context]: แอร์บุ๊ก 14 มาพร้อมตัวเครื่องอะลูมิเนียมสีเงิน (Silver) เพียงสีเดียว น้ำหนัก 1.1 กิโลกรัม
[ความคิด]: ลูกค้าถามหาสีของแอร์บุ๊ก 14 ใน Context ระบุชัดเจนว่ามีแค่สีเงินสีเดียว สมมติว่าตรงกับตัวเลือกที่ 2
Answer: 2

วิเคราะห์ทีละสเต็ป และบรรทัดสุดท้ายของการตอบกลับ **บังคับให้เขียนรูปแบบนี้เท่านั้น**:
Answer: X
(โดย X คือตัวเลขคำตอบ 1-10 เท่านั้น)"""

# --- 3. CHECKPOINT MANAGER ---
if os.path.exists(CHECKPOINT_PATH):
    print("♻️ พบไฟล์ Checkpoint! กำลังโหลดข้อมูลเดิม...")
    with open(CHECKPOINT_PATH, 'r', encoding='utf-8') as f: saved_state = json.load(f)
    results = saved_state['results']
    stats = saved_state['stats']
    processed_ids = set(saved_state['processed_ids'])
else:
    print("🆕 ไม่พบ Checkpoint เริ่มรันใหม่ข้อ 1")
    results = {model: {} for model in MODELS_TO_TEST}
    stats = {model: {"success": 0, "fallback_9": 0} for model in MODELS_TO_TEST}
    processed_ids = set()

start_time = time.time()

# --- 4. MAIN INFERENCE LOOP ---
for idx, row in tqdm(df_questions.iterrows(), total=len(df_questions), desc="📚 Answering Questions", colour='cyan'):
    q_id = str(row['id'])
    if q_id in processed_ids: continue

    q = row['question']
    choices_text = "\n".join([f"{i}. {row[f'choice_{i}']}" for i in range(1, 11)])

    # ขยายคำถาม (HyDE)
    expanded_queries = generate_expanded_queries(q)

    # ค้นหาแบบกวาดครอบคลุม + Dynamic Top K
    context = hybrid_retrieve(q, expanded_queries=expanded_queries)

    user_prompt = f"[Context]\n{context}\n\n[Question]\n{q}\n\n[Choices]\n{choices_text}\n\nวิเคราะห์และตอบคำถาม:"
    messages = [{"role": "system", "content": sys_prompt}, {"role": "user", "content": user_prompt}]

    # ให้ LLM วิเคราะห์หาคำตอบ
    for model in MODELS_TO_TEST:
        raw_ans = ask_llm(messages, model, max_tokens=1024)
        parsed_ans, is_valid = parse_cot_answer(raw_ans)

        results[model][q_id] = parsed_ans
        if is_valid and parsed_ans != 9: stats[model]["success"] += 1
        elif parsed_ans == 9: stats[model]["fallback_9"] += 1

    processed_ids.add(q_id)

    with open(CHECKPOINT_PATH, 'w', encoding='utf-8') as f:
        json.dump({'results': results, 'stats': stats, 'processed_ids': list(processed_ids)}, f, ensure_ascii=False, indent=2)

elapsed_time = time.time() - start_time
print(f"\n✅ Inference completed in {elapsed_time/60:.2f} minutes.")

# --- 5. SAVE SUBMISSIONS ---
print("📊 Generating Reports & Saving files to Google Drive...")
for model in MODELS_TO_TEST:
    model_answers = [results[model].get(str(qid), 9) for qid in df_questions['id']]
    sub_df = pd.DataFrame({'id': df_questions['id'], 'answer': model_answers})
    sub_df.to_csv(os.path.join(DRIVE_SAVE_DIR, f'submission_{model}.csv'), index=False)
    sub_df.to_csv(f'submission_{model}.csv', index=False)

print("\n" + "="*50)
print(f"📁 บันทึกไฟล์ทั้งหมดเรียบร้อยแล้วที่: {DRIVE_SAVE_DIR}")
print("="*50)

